#:schema https://coveooss.github.io/json-schema-for-humans/examples/cases/additional_properties.json


[FormatStrings]
seedText = "[badgeText][::r] îˆœ  [blue:gray:-]î‚° SEED [gray:#303030:-]î‚°[-:-:-][badgeIcon] %[3]s %[1]s %s[-:-:-]"
quickColorTitle = "[badgeText][::r] îˆ«  [blue:gray:-]î‚° QuickColor [gray:#303030:-]î‚°[-:-:-][badgeIcon] %[1]s [-:-:-]%[2]s"
quickColorPrompt = "\n[:red:-] ï„¨  [red:gray:-]î‚° [-]%[1]s [gray:green:]î‚° [green:#303030:]î‚°[-:-:-]" # [:#303030:-]î‚° [badgeText][::r] ï„¨  [blue:gray:-]î‚° %[1]s [gray:red:-]î‚° [-:-:-]
seedTextTail = "[#303030:blue:-]î‚°"
seedRoll = "[badgeText][::r] ï±¬  [blue:gray:-]î‚° ROLL [gray:red:-]î‚° #%[1]d [-:-:-][red:purple:-]î‚° [purple:#303030]î‚° [-:-:-]" # [:#303030:-]î‚°
seedRolls = "[badgeText][::r] ï±¬  [blue:gray:-]î‚° %[2]d ROLLS [gray:red:-]î‚° %[1]d [-:-:-][red:purple:-]î‚° [white]â‹¯  [purple:blue:-]î‚°[-:blue:-] %[3]d [blue:#303030:-]î‚°  [-:-:-]" # [:#303030:-]î‚°

btnReroll = " ï›  reroll "
keySchemeName = "[yellow:black:] ï Š  [::r] %[1]s [-:-:-]\n[yellow:black:] %[2]s [-:-:-]"
btnReseed = " î¯£  reseed "
tagBadgeItem = "[badgeText][%[1]s]î‚¶[::r]ï§¼[%[1]s:#303030:-]î‚° %[1]s %[5]s"
tagBadgeField = "[badgeText] î‚¶[::r]ï§¼[:#303030:-]î‚´ %[1]s [#303030:#505050]î‚¼ [:#505050][-:-:-]"
badgeField = "[badgeText]î‚¶[::r]ï§¼[:#303030:-]î‚´ %[1]s [#303030:#505050]î‚¼ [:#505050][-:-:-]"
swatchPosInfo = "[badgeText][::r]   ï €  [blue:gray:-]î‚°% 3[1]d  [gray:pink]î‚¼[black:pink] % 3[2]d [-:-:-]"
labelGroupTitle ="[badgeText][:#303030:r] ï€¬  %[1]s [blue:%[3]s:-]î‚°[#303030:%[3]s:]%[2]s[%[3]s]î‚¼[-:-:-]" 
labelGroupHeader ="[#303030:yellow] ï€¬  %[1]s [yellow:#303030:]î‚° %[2]s [#303030:-:-]î‚¼[-:-:-]" 
labelAction = "[yellow:#303030:r] ï€¬  %[1]s [yellow:#303030:-]î‚°"
toolBarLabel = "[#303030:yellow:] %[2]s [yellow:#303030:-]î‚° %[1]s [#303030:lime:-]î‚°[lime:#303030:-]î‚°"
keyTablePosInfo = "[badgeText][::r] ï €  HIGHLIGHTS [blue:gray:-]î‚° %[1]d - %[2]d of ï‚° %[3]d [gray:pink]î‚¼[black:pink] %[4]d [-:-:-]"
colorInfoName = "[#303030:yellow:r]%[1]s %[2]s %[3]s[-:-:-]"
base16ViewRows = "[#303030:yellow:r] â…©â…¥ Base16 Rows [-:-:-]"
base16ViewColumns = "[#303030:yellow:r] â…©â…¥ Base16 Columns [-:-:-]"
gridView = "[#303030:yellow:r] ï±– Grid [-:-:-]"
verticalBarsView = "[#303030:yellow:r] ï©µVertical Bars [-:-:-]"
# panelTitle = "[badgeText]ğŸ¬«[yellow:#303030] %[1]s [badgeText]ğŸ¬›[-:-:-]"  # ïš [blue:#303030:-]î‚¼ 
# î‚¾î‚¸î‚ºî‚¼
menuTitleMain = "[%[3]s]î‚¶[::r]%[1]s [:#303030:-]î‚´ [%[3]s:#303030]î‚º[#303030:%[3]s] [%[3]s:#303030:-]î‚¼ [yellow]%[2]s [%[3]s:#303030:-]î‚º[%[3]s:-]î‚¼[-:-:-]" # "[badgeText][::r] %[1]s [blue:#303030:-]î‚¼ [yellow]%[2]s [%[3]s:#303030:-]î‚º[:-:]î‚¼[-:-:-]" 
panelTitleLeft = "[red:#303030]î‚º[#303030:red] %[1]s [red:#303030:-]î‚¼ [yellow]%[2]s [red:#303030:-]î‚º[red:#303030]î‚¼[-:-:-]" # "[badgeText][::r] %[1]s [blue:#303030:-]î‚¼ [yellow]%[2]s [red:#303030:-]î‚ºî‚¼[-:-:-]" 
panelTitleCenter = "[red:#303030]î‚º[#303030:red] %[1]s [red:#303030:-]î‚¼ [yellow]%[2]s [red:#303030:-]î‚º[red:#303030]î‚¼[-:-:-]"  # [green:gray:-]î‚ºî‚¼[green:gray:-]
panelTitleRight = "[red:#303030]î‚º[#303030:red] %[1]s [red:#303030:-]î‚¼ [yellow]%[2]s [red:#303030:-]î‚º[red:#303030]î‚¼[-:-:-]" 
bigNum = "[%[1]s:%[2]s:b]%[3]s[-:-:-]"
fillrArt = "[%[1]s]"

colorFrameTitle = "[badgeText][::r] ïŠ’ [blue:#303030:-]î‚¼ [yellow]%[1]s [#303030:%[1]s:-]î‚¼  [%[1]s:#303030]î‚¼  [-:-:-]" 
colorFrameFooterIcons = "[gray:red:-]î‚° %[1]s  [red:purple:-]î‚°[#303030]  %[2]s  [purple:#303030]î‚° %[3]s  [-:-:-]"

labelSymbolBase16Colorblack = "[badgeText][#f1f1f1:%[1]s:]%02[6]d[%[1]s:#303030:]î‚° [white::]%[1]s %[7]s%[5]s"
labelSymbolBase16Color = "[badgeText][%[1]s::r][::r]%02[6]d[%[1]s:#303030:-]î‚° %[2]s %[7]s%[5]s"
labelSymbolBase16 = "[badgeText][%[1]s::r]%02[6]d[%[1]s:#303030:bd]î‚° %[2]s %[7]s%[5]s"
labelListItemBase16 = "[%[1]s]î‚¶[::r]ï§¼[%[1]s:#303030:-]î‚° %[1]s "
heartsArt='''[%[1]s][#175a6c]ğŸ­‡ğŸ­†ğŸ­‘ğŸ­†ğŸ­‘ğŸ¬¼ğŸ­‡ğŸ­†ğŸ­‘ğŸ­†ğŸ­‘ğŸ¬¼[-]
[%[1]s][#007ca9] ğŸ­§ğŸ­“ğŸ­ğŸ­œ  ğŸ­§ğŸ­“ğŸ­ğŸ­œ '''
heartArt='''[%[1]s][#175a6c]ğŸ­‡ğŸ­†ğŸ­‘ğŸ­†ğŸ­‘ğŸ¬¼[-]
[%[1]s][#007ca9] ğŸ­§ğŸ­“ğŸ­ğŸ­œ '''
logoArt = '''[-:-:-][#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[#000011:#000012]â–”[-:-:-]
[#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[:#000012]â–”[#045657:]â–—[#000012:#02d4ba]â–€[:#07c4a7]â–€[:#09b694]â–€[#085f56:#000012]â––[#000013:]â–[-:-:-][#000012:]â–ˆâ–ˆâ–ˆ[:#000012]â–”[-:-:-][#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[-:-:-]
[#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[:#000012]â–”[#000013:]â–[#016c96:#000b20]â–—[#007ca9:#023843]â–…[:#02eacb]â–…[#0080aa:#0adfbc]â––[#0df5c2:#09d5a9]â–…[#0cf5c3:#064846]â–…[#0ff3c3:#021a25]â––[#000013:#000012]â–[-:-:-][#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[:#000012]â–”[-:-:-][#000012:]â–ˆâ–ˆ[-:-:-]
[#000012:]â–ˆâ–ˆâ–ˆâ–ˆ[#66363a:#050214]â–[#fd8174:#0c0617]â–[#fb378e:#0c0318]â–[#fb1ea8:#0c0219]â–[#32052e:#e01b98]â–[#d02097:#006992]â–‹[#006b94:#01213a]â–Š[#000a1e:#0e2269]â–[#c07873:#112269]â–[#c07871:#0a1b27]â–Š[#052b34:#0ecda7]â–[#df2098:#12caa8]â–[#e41b97:#4a0b3d]â–Š[#fb1fa8:#0c0219]â–[#fa388c:#0c0318]â–[#fe8175:#0c0617]â–[#572d34:#040214]â–[#000012:#000012]â–”â–”[-:-:-][#000012:]â–ˆâ–ˆ[-:-:-]
[#000012:#000012]â–”[-:-:-][#000012:]â–ˆ[#1c0531:#000012]â–•[#761395:#000013]â–…[#17042c:#9a2d8c]â–˜[#97169e:#fd8274]â–…[#6f0c96:#fc378d]â–…[#4a0f96:#fc1ca6]â–…[#182357:#bd1085]â–…[#87116e:#062840]â–˜[#00273c:#00071a]â–Š[#000011:#132075]â–[#fc8477:#161f73]â–[#fd8476:#0b0714]â–Š[#0cb395:#0c091e]â–…[#0ff3c4:#342751]â––[#152655:#b80f85]â–…[#441e99:#fc1da6]â–…[#671593:#fb388a]â–…[#175a6c:#fd8274]â–…[#905759:#0b2254]â–˜[#111c66:#000012]â–…[#010218:]â–[#000012:]â–”[-:-:-][#000012:]â–ˆ[-:-:-]
[#000012:]â–ˆâ–ˆâ–ˆâ–ˆ[#0d091f:#000012]â–[#100b22:]â–€[#000013:#440753]â–Š[#8e0a99:#040016]â–€[#442272:#012338]â–˜[#003e4f:#002136]â–˜[#002135:#000617]â–Š[#000011:#131f75]â–[#fc8477:#161f74]â–[#fb8576:#0c0712]â–Š[#051b22:#0df5c3]â–[#002b3f:#0ef3c3]â–[#038586:#002438]â–[#01f0d0:#010918]â–€[#06706c:#0a0119]â–[#a70d7f:#050015]â–€[#6f085a:#010013]â–˜[#000012:#000012]â–”[-:-:-][#000012:]â–ˆâ–ˆâ–ˆ[-:-:-]
[#000012:]â–ˆâ–ˆ[:#000012]â–”â–”[-:-:-][#000012:]â–ˆ[:#000012]â–”â–”[-:-:-][#000012:]â–ˆ[:#001f33]â–ƒ[#000f21:#00263a]â–ƒ[#002135:#000618]â–Š[#0e185a:#000013]â–”[#885377:#030214]â–”[#c0665d:#040213]â–”[#041c25:#0df5c3]â–[#001a2d:#0ff3c3]â–[#000012:#002034]â–ƒ[#000013:#000012]â–•[#000012:]â–”[-:-:-][#000012:]â–ˆâ–ˆ[:#000012]â–”â–”[-:-:-][#000012:]â–ˆâ–ˆ[-:-:-]
[#000012:#000012]â–”[-:-:-][#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[:#000012]â–”[-:-:-][#000012:]â–ˆ[:#000012]â–”[#001d30:]â–[#002135:#000617]â–Š[#000012:#000012]â–”â–”â–”[#000011:#0bb997]â–‚[#0ef3c3:#02252b]â–˜[#000012:#000012]â–”â–”[-:-:-][#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[-:-:-]
[#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[#001b2f:#000012]â–[#00182c:]â–€[#000012:]â–”[-:-:-][#000012:]â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ[-:-:-]
[#000012:#000012]â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”[-:-:-][#000012:]â–ˆ[-:-:-]
6a]â–…[#001528:#001628]â–[:#011629]â–â–â–â–â–â–â–â–[#001427:#011528]â–[-:-:-]'''

lightRocker='''
 â–â– â–   â– â–â– 
î‚ºâ–ˆî‚¼î‚ºî‚¼ ğŸ¬“ î‚¾î‚¸î‚¾â–ˆî‚¸
î‚¾â–ˆî‚¸î‚¾î‚¸ ğŸ¬Œ î‚ºî‚¼î‚ºâ–ˆî‚¼
 ğŸ­¶ğŸ­¶ ğŸ­¶   ğŸ­¶ ğŸ­¶ğŸ­¶
'''
satRocker='''
 â–â– â–   â– â–â– 
î‚ºâ–ˆî‚¼î‚ºî‚¼ ğŸ¬š î‚¾î‚¸î‚¾â–ˆî‚¸
î‚¾â–ˆî‚¸î‚¾î‚¸ ğŸ¬ î‚ºî‚¼î‚ºâ–ˆî‚¼
 ğŸ­¶ğŸ­¶ ğŸ­¶   ğŸ­¶ ğŸ­¶ğŸ­¶
'''
hueRocker='''
 â–â– â–   â– â–â– 
î‚ºâ–ˆî‚¼î‚ºî‚¼ğŸ¬ğŸ¬¦ î‚¾î‚¸î‚¾â–ˆî‚¸
î‚¾â–ˆî‚¸î‚¾î‚¸ğŸ¬‰ğŸ¬Š î‚ºî‚¼î‚ºâ–ˆî‚¼
 ğŸ­¶ğŸ­¶ ğŸ­¶   ğŸ­¶ ğŸ­¶ğŸ­¶
'''
pasteStartupPanel = '''
Paste the content of your clipboard now!
'''
startupContinuePalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Load the most recent palette worked on. [-:-:-]

[detailText] This description is silly since. [-:-:-]

[detailText] %[4]s [-:-:-]

[#505050::b]All standard features available.[::-]
'''
startupBlankPalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Start with no colors just you and the abyss. [-:-:-]

[detailText] Add colors manually or utilize the many nifty tools and abilities for finding colors. [-:-:-]

[#505050::b]All standard features available.[::-]
'''
startupPastePalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Paste any content from your clipboard and find all [white:#c55c55:b]#C55C55[-:-][detailText] colors. [-:-:-]

[detailText] Should support [red]bracketed paste [fuchsia]OSC 52 [yellow]simple paste [-:-:-]

[#505050::b]All standard features available.[::-]
'''
startupRandomPalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Start with diverse set of colors that probably doesn't match! [-:-:-]

[detailText] Roll the dice and find some colors to begin your [teal]palettic[blue] adventure with. Begin with [pink]ugly[blue] and [olive]shape[blue] them to a [fuchsia]beautiful[blue] [white]gradient[blue] for your needs![-:-:-]

[#505050::b]All standard features available.[::-]
'''
startupScriptedPalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Code your way to colorvana, using simple JS and popular colr, chroma, and other libraries. [-:-:-]

[#505050::b]All standard features available.[::-]
'''
startupPluginPalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Use a plugin's startup features. [-:-:-]

[#505050::b][yellow]Some[#505050] standard features available.[::-]
'''
startupQueryPalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Query your terminal's palette with OSC 4 to get the base 16 indexed colors and OSC 10-19 for cursor, selection, and mouse colors. [#505050::b]( ^]4?? ). [-:-:-]

[detailText] Does not support any terminal multiplexer/pseudo-terminal other than [red::i]tmux[-:-:-]

[detailText] Must have tmux [red::i]allow-passthrough on[-:-:-] 

[#505050::b]All standard features available.[::-]
'''
startupLoadPalette = '''
[%[3]s::r] %[1]s [-:-:-] %[2]s

[detailText] Continue a previous session. [-:-:-]

[#505050::b][red]Most[#505050] standard features available.[::-]
'''


badgeThreeLineField = '''[badgeText]       [#303030:-]î‚¼ [:#505050]
[badgeText] î‚¶[::r]%[1]s [:#303030:-]î‚´ [#303030:-]î‚¼ [:#505050]
[badgeText]     [#303030:-]î‚¼ [:#505050]'''

newFunctionTemplate = '''
function %s(){
  for (var i = 0; i < 16; i++) {
    var col = chroma.hcl(
      seed.InRange(1, 360),
      seed.InRange(20,70),
      seed.InRange(20,50)
    );
    data.push(col.hex());
  }
}
'''

functionCallerTemplate = '''function userFunction(_,chroma,husl,hsluv,helpers,$,seed){
  %s
  return %s()
}
callUserFn(userFunction)
'''

[TagStyles]

  [TagStyles.fuzzMatched]
    Attributes = "b"
    BG = "#303030"
    FG = "magenta"

  [TagStyles.action]
    Attributes = "b"
    BG = "yellow"
    FG = "red"

  [TagStyles.background]
    Attributes = "r"
    BG = "#303030"
    FG = "white"

  [TagStyles.badgeIcon]
    Attributes = ""
    BG = "#505050"
    FG = "yellow"

  [TagStyles.oscIdx]
    Attributes = ""
    BG = ""
    FG = "red"

  [TagStyles.detailText]
    Attributes = ""
    BG = ""
    FG = "blue"

  [TagStyles.badgeText]
    Attributes = ""
    BG = "#313131"
    FG = "blue"

  [TagStyles.baseColorTagaqua]
    Attributes = "r"
    BG = ""
    FG = "aqua"

  [TagStyles.baseColorTagblack]
    Attributes = "r"
    BG = ""
    FG = "black"

  [TagStyles.baseColorTagblue]
    Attributes = "r"
    BG = ""
    FG = "blue"

  [TagStyles.baseColorTagfuchsia]
    Attributes = "r"
    BG = ""
    FG = "fuchsia"

  [TagStyles.baseColorTaggray]
    Attributes = "r"
    BG = "#000000"
    FG = "gray"

  [TagStyles.baseColorTaggreen]
    Attributes = "r"
    BG = ""
    FG = "green"

  [TagStyles.baseColorTaglime]
    Attributes = "r"
    BG = ""
    FG = "lime"

  [TagStyles.baseColorTagmaroon]
    Attributes = "r"
    BG = ""
    FG = "maroon"

  [TagStyles.baseColorTagnavy]
    Attributes = "r"
    BG = ""
    FG = "navy"

  [TagStyles.baseColorTagolive]
    Attributes = "r"
    BG = ""
    FG = "olive"

  [TagStyles.baseColorTagpurple]
    Attributes = "r"
    BG = ""
    FG = "purple"

  [TagStyles.baseColorTagred]
    Attributes = "r"
    BG = ""
    FG = "red"

  [TagStyles.baseColorTagsilver]
    Attributes = "r"
    BG = ""
    FG = "silver"

  [TagStyles.baseColorTagteal]
    Attributes = "r"
    BG = ""
    FG = "teal"

  [TagStyles.baseColorTagwhite]
    Attributes = "r"
    BG = ""
    FG = "white"

  [TagStyles.baseColorTagyellow]
    Attributes = "r"
    BG = ""
    FG = "yellow"

  [TagStyles.consoleIcon]
    Attributes = ""
    BG = "#303030"
    FG = "blue"

  [TagStyles.consoleMsg]
    Attributes = "r"
    BG = "black"
    FG = "blue"

  [TagStyles.consoleMsgDebug]
    Attributes = "r"
    BG = "black"
    FG = "pink"

  [TagStyles.consoleMsgErr]
    Attributes = "r"
    BG = "black"
    FG = "red"

  [TagStyles.consoleMsgPlugin]
    Attributes = "r"
    BG = "black"
    FG = "green"

  [TagStyles.consoleMsgPluginErr]
    Attributes = "r"
    BG = "black"
    FG = "red"

  [TagStyles.consoleMsgWarn]
    Attributes = "r"
    BG = "black"
    FG = "yellow"

  [TagStyles.cursor]
    Attributes = ""
    BG = ""
    FG = "orange"

  [TagStyles.fieldInput]
    Attributes = ""
    BG = "#303030"
    FG = "green"

  [TagStyles.fieldPlaceholder]
    Attributes = ""
    BG = "red"
    FG = "#303030"

  [TagStyles.fieldIcon]
    Attributes = ""
    BG = "pink"
    FG = "#303030"

  [TagStyles.fieldLabel]
    Attributes = ""
    BG = "blue"
    FG = "#303030"

  [TagStyles.foreground]
    Attributes = ""
    BG = ""
    FG = "white"

  [TagStyles.input_autocomplete]
    Attributes = ""
    BG = "#373e48"
    FG = "red"

  [TagStyles.input_field]
    Attributes = ""
    BG = "#373e48"
    FG = "blue"

  [TagStyles.input_placeholder]
    Attributes = ""
    BG = "#2c3139"
    FG = "yellow"

  [TagStyles.list_main]
    Attributes = ""
    BG = ""
    FG = "green"

  [TagStyles.list_second]
    Attributes = ""
    BG = ""
    FG = "blue"

  [TagStyles.paletteTagsIcon]
    Attributes = ""
    BG = "#5c6370"
    FG = "yellow"

  [TagStyles.paletteTagsInfo]
    Attributes = ""
    BG = "yellow"
    FG = "black"

  [TagStyles.palette_name]
    Attributes = "b"
    BG = "red"
    FG = "white"

  [TagStyles.qcStatusInfo]
    Attributes = "b"
    BG = "black"
    FG = "green"

  [TagStyles.scriptConsoleErr]
    Attributes = "r"
    BG = "black"
    FG = "red"

  [TagStyles.scriptConsoleMsg]
    Attributes = "r"
    BG = "black"
    FG = "green"

  [TagStyles.shortcut]
    Attributes = ""
    BG = "#343434"
    FG = ""

  [TagStyles.shortcutAction]
    Attributes = ""
    BG = "#343434"
    FG = "yellow"

  [TagStyles.shortcutIcon]
    Attributes = ""
    BG = "#343434"
    FG = "teal"

  [TagStyles.shortcutKey]
    Attributes = ""
    BG = "#343434"
    FG = "red"

  [TagStyles.shortcutKeys]
    Attributes = ""
    BG = "#343434"
    FG = ""

  [TagStyles.shortcutLink]
    Attributes = ""
    BG = "red"
    FG = "teal"

  [TagStyles.shortcutModifier]
    Attributes = ""
    BG = "teal"
    FG = "#343434"

  [TagStyles.tblSortAsc]
    Attributes = "rb"
    BG = "black"
    FG = "blue"

  [TagStyles.tblSortDesc]
    Attributes = "rb"
    BG = "black"
    FG = "yellow"

  [TagStyles.titleIcon]
    Attributes = ""
    BG = "red"
    FG = "#343434"

  [TagStyles.titleText]
    Attributes = ""
    BG = "#343434"
    FG = "red"
  [TagStyles.gridMarked]
    Attributes = ""
    FG = "#F2812F"
    BG = "#212121"
  [TagStyles.buttonSelection]
    Attributes = ""
    FG = "#f0f0f0"
    BG = "#212121"
  [TagStyles.gridSelection]
    Attributes = ""
    FG = "#f0f0f0"
    BG = "#212121"
# version = 2
# seedRolls = "[badgeText][::r] %[2]d ï±¬  ROLLS [-:-:-][badgeIcon][::r] [yellow:purple:-]î‚° [purple:blue:-]î‚°[-:blue:-] %[1]d [blue:pink:-]î‚° #%[3]d [-:-:-]" # [:#303030:-]î‚°
# tagBadgeItem = "[badgeText][%[1]s]î‚¶[::r]ï§¼[%[1]s:#303030:-]î‚° %[1]s [#303030:pink]î‚¼ %[2]d [pink]î‚´[-:-:-]"
# ï±– ï©¬ï©µ
# labelSymbolBase16maroon = "[badgeText][%[1]s]î‚¶[::r]ğŸğŸ”[%[1]s:#303030:-]î‚° %[1]s %[5]s"
# labelSymbolBase16green =  "[badgeText][%[1]s]î‚¶[::r]ğŸ™ğŸ[%[1]s:#303030:-]î‚° %[1]s %[5]s"
# labelSymbolBase16olive =  "[badgeText][%[1]s]î‚¶[::r]ğŸ£ğŸ¨[%[1]s:#303030:-]î‚° %[1]s %[5]s"
# labelSymbolBase16navy =   "[badgeText][%[1]s]î‚¶[::r]ğŸ­ğŸ²[%[1]s:#303030:-]î‚° %[1]s %[5]s"
# labelSymbolBase16teal =   "[badgeText][%[1]s]î‚¶[::r]ğŸ·ğŸ¼[%[1]s:#303030:-]î‚° %[1]s %[5]s"
